name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t itsmeakhil:latest .
        docker tag itsmeakhil:latest ${{ secrets.DOCKER_USERNAME }}/itsmeakhil:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/itsmeakhil:latest

    - name: SSH into EC2 and deploy
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          # Pull the latest Docker image
          docker pull ${{ secrets.DOCKER_USERNAME }}/itsmeakhil:latest
          
          # Stop the running container if it exists
          docker stop itsmeakhil || true
          docker rm itsmeakhil || true
          
          # Run the new container
          docker run -d -p 80:80 --name itsmeakhil ${{ secrets.DOCKER_USERNAME }}/itsmeakhil:latest
